apiVersion: apps/v1
kind: Deployment
metadata:
  name: mits-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mits
  template:
    metadata:
      labels:
        app: mits
    spec:
      containers:
      - name: mits-app
        image: mits-app:v1
        imagePullPolicy: Never 
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mits-service
spec:
  type: NodePort
  selector:
    app: mits
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007